# Missing upstream: nothing. fmt ships CMake, exports fmt::fmt and installs a
# fmt.pc, so this port is the same short list every well-behaved library gets
# -- where to find it, what it answers to, what it is under.
#
# It is here because find_package(fmt) is a question this build answers, and
# a library that carries its own copy of fmt can then be given this one
# instead.
#
# The newest release, which took two patches to reach and both of them are
# about includes rather than about fmt.
#
# 12.2.0 made fmt/core.h include base.h alone, so a consumer that included
# it and called fmt::format stopped compiling; and it moved the std::byte
# formatter from fmt/format.h to fmt/std.h, so a consumer that formats a
# range of bytes and includes neither gets "unknown format specifier" out
# of a compile-time format string check. openal-soft does both, and its
# port carries the two includes that say so.
#
# fmt puts its major in an inline namespace, so a program compiled against
# 11 does not link against 12. There is one fmt in a build here.
cme_declare_port(
  NAME fmt
  PROVIDES fmt
  VERSION 12.2.0
  GITHUB_REPOSITORY fmtlib/fmt
  GIT_TAG 12.2.0
  GIT_TAG_TEMPLATE "@VERSION@"
  OPTIONS
    # Its install target is generated by default, and an install(EXPORT) is
    # checked while generating even when nothing will run it.
    "FMT_INSTALL OFF"
    "FMT_TEST OFF"
    "FMT_DOC OFF"
    "FMT_FUZZ OFF"
  SYSTEM_PKGCONFIG "fmt:fmt::fmt"
  # An installed copy is asked whether it can do what this build needs of
  # it, which is more than formatting an integer: a distribution ships
  # whichever fmt it ships -- Debian sid has 10.1, Fedora has 12.1 -- and
  # the majors are not interchangeable in either direction.
  #
  # So the probe is what the build actually asks of it: a range of
  # std::byte with a nested specifier, which is how openal-soft prints an
  # unrecognised HRTF header. A copy that cannot compile this is a copy
  # this build cannot use, whoever installed it and whatever version it
  # calls itself.
  SYSTEM_CODE "#include <array>
#include <cstddef>
#include <fmt/format.h>
#include <fmt/ranges.h>
#include <fmt/std.h>
int main() {
  std::array<std::byte, 2> header{};
  return fmt::format(\"{::#04X}\", header).empty() ? 1 : 0;
}"
  LICENSE MIT
  # What this library answers to when something asks the linker for it by
  # name. A bare -l finds whatever is installed; a target is an archive
  # with a path.
  LINK_NAMES
    "fmt=fmt::fmt"
  # What a consumer links. Said here so that something other than a
  # human can check that the port still produces it.
  TARGETS fmt::fmt
  CHECK_HEADER fmt/format.h
)

function(cme_adapt_fmt source binary)
  # fmt makes the alias itself; this is here for the case where it stops.
  cme_alias(fmt::fmt fmt)
  cme_export_variable(fmt fmt_FOUND TRUE)
  cme_export_variable(fmt fmt_VERSION 12.2.0)
endfunction()
