# Missing upstream: nothing. Abseil ships CMake, exports `absl::` targets and
# installs a pkg-config file for each of them, so this port is where to find
# it, what it answers to, and one option that is not a nicety.
#
# It is here because re2 asks for it by this name and nothing else in this
# registry does. Abseil is one library with some hundreds of targets: what a
# consumer links is whichever few of them it names, so the list below is what
# re2 links and what anything else is likely to.
#
# ABSL_PROPAGATE_CXX_STD is the one that matters. Abseil compiled as C++17 and
# used from C++20 disagrees with itself about what `absl::string_view` and
# `absl::optional` are -- its own types in one and the standard ones in the
# other -- and the program links and then does not run. On, it is compiled with
# whatever standard the consumer is compiled with, which is the only way a
# build with one of each ends up with one Abseil.
cme_declare_port(
  NAME absl
  PROVIDES absl
  VERSION 20250127.0
  GITHUB_REPOSITORY abseil/abseil-cpp
  GIT_TAG 20250127.0
  GIT_TAG_TEMPLATE "@VERSION@"
  OPTIONS
    "ABSL_PROPAGATE_CXX_STD ON"
    # Its install rules are generated by default, and an install(EXPORT) is
    # checked while generating even where nothing will run it.
    "ABSL_ENABLE_INSTALL ON"
    "ABSL_BUILD_TESTING OFF"
    "BUILD_TESTING OFF"
  SYSTEM_PKGCONFIG "absl_strings:absl::strings"
  LICENSE Apache-2.0
  # What this library answers to when something asks the linker for it by
  # name. A bare -l finds whatever is installed; a target is an archive with a
  # path.
  LINK_NAMES
    "absl_base=absl::base"
    "absl_strings=absl::strings"
  # What a consumer links. Said here so that something other than a human can
  # check that the port still produces it.
  TARGETS absl::base absl::strings absl::flat_hash_map absl::span
  CHECK_HEADER absl/strings/str_cat.h
)
