# Missing upstream: CMake, in the sense this registry means it -- Skia builds
# with GN, and its own GN-to-CMake script says it is "not meant for any
# purpose beyond development" in an IDE.
#
# So GN is asked to describe the build and the description becomes CMake
# targets: see cmake/gn.cmake, which knows nothing about Skia. Everything in
# this file is Skia's own vocabulary, and that is the only Skia-specific
# thing in the repository.
#
# Two rules shape what follows.
#
# Nothing by default. The port with no features is Skia as a CPU rasteriser:
# no GPU backend, no codecs, no fonts, no compression, no PDF, no SVG. A
# consumer asks for what it uses and gets a build of that, rather than paying
# for what somebody thought was a reasonable default.
#
# Nothing bundled, ever. Skia carries copies of zlib, libpng, libjpeg-turbo,
# libwebp, freetype, expat and more in third_party/externals, and every
# feature here that needs one of them turns on the matching
# skia_use_system_* and names the port that supplies it. Those settings are
# read back from GN afterwards rather than assumed. And since this build
# never runs Skia's dependency sync, third_party/externals is empty: a
# bundled path would not quietly happen, it would fail to find its sources.
# The versions this port can build, as archives with a digest of each. Not a
# clone: Skia's history is several gigabytes and none of it is read here, and
# an archive of a commit is a fixed number of bytes that can be checked.
include("${CMAKE_CURRENT_LIST_DIR}/versions.cmake")

cme_declare_port(
  NAME skia
  PROVIDES Skia skia SKIA
  # The newest milestone in versions.cmake. cme_version(skia 148) takes
  # another; a number that is not listed is refused, because there is no
  # digest for it.
  VERSION 153
  # Its AHardwareBuffer code on Android includes vulkan_core.h whether or
  # not there is a Vulkan backend in this build, so the headers are needed
  # even by a build that asked for GL and nothing else. Headers only: no
  # loader, no driver.
  # Its own description names both of these whether or not the features
  # that use them are on: //:skia links expat and includes vulkan_core.h,
  # with skia_use_expat=false and no Vulkan backend. What a build says it
  # links is what it links.
  DEPENDS vulkan-headers expat
  # What the module called skia is, without saying that an installed one
  # will do. A project inside this build that asks pkg-config for skia --
  # skiff does -- is asking for this library, and answering it with the
  # machine's copy while everything else links the one built here puts two
  # Skias in one program. What an installed Skia was built with cannot be
  # read from a .pc file, though, and this port's features are exactly
  # that, so it is not offered as a way to find one.
  PKGCONFIG_NAMES skia
  # An installed Skia, where there is one. Debian and Ubuntu ship libskia-dev
  # with a skia.pc, and the .pc says nothing about what that Skia was built
  # with -- its Cflags are one -I and its Libs are one -lskia. So every
  # feature below that can be is checked by linking a program that uses it,
  # which is the only question this library can be asked.
  SYSTEM_PKGCONFIG "skia:Skia::skia"
  GN_TARGETS "//:skia=Skia::skia"
  # //:skia.h is generated by a step that runs gn itself, from this path
  # inside the checkout, to ask which headers the library has.
  GN_IN_TREE "bin/gn"
  GN_ARGS
    "is_official_build=true"
    "is_component_build=false"
    "cc=\"@CC@\""
    "cxx=\"@CXX@\""
    # Skia's own name for a compiler cache. Without it a second build of the
    # same Skia is five hundred compiles again.
    "cc_wrapper=\"@CC_WRAPPER@\""
    "target_os=\"@TARGET_OS@\""
    "target_cpu=\"@TARGET_CPU@\""
    # No GPU. Ganesh and Graphite are both backends, and a backend is a
    # feature.
    "skia_enable_ganesh=false"
    "skia_enable_graphite=false"
    "skia_use_gl=false"
    "skia_use_egl=false"
    "skia_use_vulkan=false"
    "skia_use_metal=false"
    "skia_use_direct3d=false"
    "skia_use_dawn=false"
    "skia_use_webgl=false"
    "skia_use_webgpu=false"
    "skia_use_angle=false"
    "skia_use_x11=false"
    # No codecs.
    "skia_use_libpng_decode=false"
    "skia_use_libpng_encode=false"
    "skia_use_libjpeg_turbo_decode=false"
    "skia_use_libjpeg_turbo_encode=false"
    "skia_use_libwebp_decode=false"
    "skia_use_libwebp_encode=false"
    "skia_use_libavif=false"
    "skia_use_libjxl_decode=false"
    "skia_use_wuffs=false"
    "skia_use_dng_sdk=false"
    "skia_use_piex=false"
    "skia_use_ndk_images=false"
    # No fonts and no text shaping.
    "skia_use_freetype=false"
    "skia_use_fontconfig=false"
    # Android's own font manager, which reads the system font configuration
    # through the NDK and includes ICU's headers to do it. It is on by
    # default for any Android build with freetype, and a sysroot that has
    # no ICU stops at unicode/uchar.h. A font manager is a feature here,
    # and this one has not been asked for.
    "skia_enable_fontmgr_android_ndk=false"
    "skia_enable_fontmgr_android=false"
    "skia_use_fontations=false"
    "skia_use_harfbuzz=false"
    "skia_use_icu=false"
    "skia_use_bidi=false"
    "skia_enable_skunicode=false"
    # Things Skia turns on for itself, which reach outside the checkout.
    # PartitionAlloc is Chromium's allocator, on by default in a standalone
    # build with Clang; Perfetto is Chromium's tracing, on by default on
    # Linux. Both live in third_party/externals, and this build has no
    # externals at all. Neither is something a library consumer asked for.
    "skia_use_partition_alloc=false"
    "skia_use_perfetto=false"
    # Only used for fuzzing, and only builds a fuzzer.
    "skia_provide_default_fuzz_engine=false"
    # A Windows document format.
    "skia_use_xps=false"
    # No compression, no document formats, no modules, no tools.
    "skia_use_zlib=false"
    "skia_use_expat=false"
    "skia_use_ffmpeg=false"
    "skia_use_lua=false"
    "skia_enable_pdf=false"
    "skia_enable_svg=false"
    "skia_enable_skottie=false"
    "skia_enable_tools=false"
    "extra_cflags=[@SYSROOT_FLAG@@DEP_INCLUDES@]"
    "extra_ldflags=[@SYSROOT_FLAG@@DEP_LIBDIRS@]"
  GN_CONFIRM
    "is_official_build=true"
  LICENSE BSD-3-Clause
  # What a consumer links. Said here so that something other than a
  # human can check that the port still produces it.
  TARGETS Skia::skia
  CHECK_HEADER skia/core/SkCanvas.h
  # Whether an installed Skia can be linked against by this build at all.
  #
  # findUniform takes a std::string_view, so its name says which standard
  # library the library was compiled against: libc++ writes std::__1 into it
  # and libstdc++ does not. Debian builds its libskia with g++, and a build
  # using libc++ resolves everything whose signature mentions no std type --
  # which is most of what a feature probe names -- and then fails on this
  # one, in the consumer's own link, after everything else has succeeded.
  SYSTEM_CODE "#include <skia/effects/SkRuntimeEffect.h>
#include <string_view>
int main() {
  const SkRuntimeEffect::Uniform *(SkRuntimeEffect::*fn)(std::string_view)
      const = &SkRuntimeEffect::findUniform;
  return fn == nullptr;
}"
)

# The names below are ours. Skia has no find_package convention to obey
# because nobody ever wrote one, so a consumer asks for "the Vulkan backend"
# rather than having to know it is spelled skia_use_vulkan.

cme_port_feature(skia gl
  SUMMARY "the Ganesh backend on OpenGL"
  GN_ARGS "skia_enable_ganesh=true" "skia_use_gl=true"
  GN_CONFIRM "skia_use_gl=true"
  # Taking the address is enough to need the symbol at link time, and naming
  # the overload keeps it unambiguous.
  SYSTEM_CODE "#include <skia/gpu/ganesh/gl/GrGLDirectContext.h>
int main() {
  sk_sp<GrDirectContext> (*fn)(sk_sp<const GrGLInterface>) =
      &GrDirectContexts::MakeGL;
  return fn == nullptr;
}")

# EGL is a way of reaching GL, not an alternative to it.
cme_port_feature(skia egl
  SUMMARY "Ganesh on GL, reaching it through EGL"
  IMPLIES gl
  GN_ARGS "skia_use_egl=true"
  GN_CONFIRM "skia_use_egl=true"
  SYSTEM_CODE "#include <skia/gpu/ganesh/gl/egl/GrGLMakeEGLInterface.h>
int main() {
  sk_sp<const GrGLInterface> (*fn)() = &GrGLInterfaces::MakeEGL;
  return fn == nullptr;
}")

# The other way to reach it, which is X11's: a client whose context was made
# through GLX needs a Skia assembled through GLX.
cme_port_feature(skia x11
  SUMMARY "Ganesh on GL, reaching it through GLX"
  IMPLIES gl
  GN_ARGS "skia_use_x11=true"
  GN_CONFIRM "skia_use_x11=true"
  SYSTEM_CODE "#include <skia/gpu/ganesh/gl/glx/GrGLMakeGLXInterface.h>
int main() {
  sk_sp<const GrGLInterface> (*fn)() = &GrGLInterfaces::MakeGLX;
  return fn == nullptr;
}")

# No rule tying gl to egl or x11. Skia's own factories for those are one way
# to get a GL interface and not the only one: GrGLMakeAssembledInterface
# builds it from a loader the consumer supplies, and a consumer that made the
# GL context has one. A Skia with gl and neither factory is a usable Skia for
# such a consumer, and Debian ships exactly that.

cme_port_feature(skia vulkan
  SUMMARY "the Ganesh backend on Vulkan"
  GN_ARGS "skia_enable_ganesh=true" "skia_use_vulkan=true"
  GN_CONFIRM "skia_use_vulkan=true")

cme_port_feature(skia graphite
  SUMMARY "the Graphite backend"
  GN_ARGS "skia_enable_graphite=true")

# Each codec names the port that supplies it and the argument that makes Skia
# take it from there rather than from its own third_party copy.
cme_port_feature(skia png
  SUMMARY "PNG, through libpng"
  DEPENDS libpng
  GN_ARGS "skia_use_libpng_decode=true" "skia_use_libpng_encode=true"
          "skia_use_system_libpng=true"
  GN_CONFIRM "skia_use_system_libpng=true"
  SYSTEM_CODE "#include <skia/codec/SkPngDecoder.h>
int main() {
  std::unique_ptr<SkCodec> (*fn)(sk_sp<const SkData>, SkCodec::Result*,
                                 SkCodecs::DecodeContext) = &SkPngDecoder::Decode;
  return fn == nullptr;
}")

cme_port_feature(skia jpeg
  SUMMARY "JPEG, through libjpeg-turbo"
  DEPENDS libjpeg-turbo
  GN_ARGS "skia_use_libjpeg_turbo_decode=true"
          "skia_use_libjpeg_turbo_encode=true"
          "skia_use_system_libjpeg_turbo=true"
  GN_CONFIRM "skia_use_system_libjpeg_turbo=true"
  SYSTEM_CODE "#include <skia/codec/SkJpegDecoder.h>
int main() {
  std::unique_ptr<SkCodec> (*fn)(sk_sp<const SkData>, SkCodec::Result*,
                                 SkCodecs::DecodeContext) = &SkJpegDecoder::Decode;
  return fn == nullptr;
}")

cme_port_feature(skia webp
  SUMMARY "WebP, through libwebp"
  DEPENDS libwebp
  GN_ARGS "skia_use_libwebp_decode=true" "skia_use_libwebp_encode=true"
          "skia_use_system_libwebp=true"
  GN_CONFIRM "skia_use_system_libwebp=true"
  SYSTEM_CODE "#include <skia/codec/SkWebpDecoder.h>
int main() {
  std::unique_ptr<SkCodec> (*fn)(sk_sp<const SkData>, SkCodec::Result*,
                                 SkCodecs::DecodeContext) = &SkWebpDecoder::Decode;
  return fn == nullptr;
}")

# No SYSTEM_CODE here, and not for want of trying: deflate is something Skia
# uses, not something it offers. Nothing in the public interface appears or
# disappears with it, so an installed Skia cannot be asked whether it has
# zlib -- which is why this one is reported as taken at its word rather than
# checked. A feature that cannot be observed is a fact about the library, and
# saying so is better than a probe that tests something else and passes.
cme_port_feature(skia zlib
  SUMMARY "deflate, which PDF and freetype both want"
  DEPENDS zlib
  GN_ARGS "skia_use_zlib=true" "skia_use_system_zlib=true"
  GN_CONFIRM "skia_use_system_zlib=true")

# FreeType reads compressed font tables, so it wants zlib whether or not
# anything else in the build does.
cme_port_feature(skia freetype
  SUMMARY "glyph rasterisation through FreeType"
  IMPLIES zlib
  DEPENDS freetype
  GN_ARGS "skia_use_freetype=true" "skia_use_system_freetype2=true"
          "skia_use_freetype_zlib_bundled=false"
          # Skia takes the system FreeType's headers as a path, and its
          # default for that path is /usr/include/freetype2. Left alone, a
          # machine that has FreeType installed would be compiled against
          # those headers and linked against the one built here.
          "skia_system_freetype2_include_path=\"@INCLUDE:freetype@\""
  GN_CONFIRM "skia_use_system_freetype2=true"
  # The font manager that scans a directory is implemented with FreeType and
  # compiled only when FreeType is on, so a program that names it links
  # against a Skia that has it and does not against one that has not.
  SYSTEM_CODE "#include <skia/ports/SkFontMgr_directory.h>
int main() {
  sk_sp<SkFontMgr> (*fn)(const char *) = &SkFontMgr_New_Custom_Directory;
  return fn == nullptr;
}")

# How Skia reaches GL, which it will not work out for itself.
#
# Its own build picks the file that assembles a GL interface by asking, in
# order, whether this is Android, whether EGL was asked for, whether WebGL
# was, and whether this is Linux with X11 -- and if none of those, it takes
# GrGLMakeNativeInterface_none.cpp, which returns nothing. So on a desktop
# Linux, gl without egl or x11 compiles, links, and hands back a null
# interface at run time.
#
# This port does not require one of the two: a program that reaches GL some
# other way, or assembles the interface itself out of the loader it already
# has, is a program this has no business refusing. What it does say is that
# asking for both is asking for one of them to be ignored.
# Where Emscripten is, for a build that is going to WebAssembly.
#
# Skia builds for wasm against a copy of emsdk it expects under
# third_party/externals, and puts
# --sysroot=$skia_emsdk_dir/upstream/emscripten/cache/sysroot on every
# compile and every link. This build never syncs Skia's dependencies, so
# that directory holds nothing: the compiler is told to look for the C
# library in an empty tree and <string.h> is not found. The SDK doing the
# compiling is the one to name.
#
# A platform feature: nothing asks for it and nothing can refuse it, it is
# on because this build is going to WebAssembly.
cme_port_feature(skia wasm
  SUMMARY "building against the Emscripten SDK that is doing the compiling"
  GN_ARGS "skia_emsdk_dir=\"@EMSDK@\"")

# Skia asks about EGL before it asks about X11 and takes the first answer,
# so a build told both is a build where one of them was ignored. Which one
# matters: a GL context made through GLX and an interface assembled through
# EGL do not fit together, and what that looks like is a null interface at
# run time rather than an error at build time.
cme_port_rule(skia AT_MOST_ONE_OF egl x11)

# A font database is not a font rasteriser: fontconfig says which file, and
# FreeType turns it into glyphs.
cme_port_feature(skia fontconfig
  SUMMARY "finding fonts through the system's fontconfig"
  IMPLIES freetype
  GN_ARGS "skia_use_fontconfig=true" "skia_enable_fontmgr_fontconfig=true"
  GN_CONFIRM "skia_use_fontconfig=true")

cme_port_feature(skia fontmgr-directory
  SUMMARY "loading fonts from a directory, with no system font database"
  IMPLIES freetype
  GN_ARGS "skia_enable_fontmgr_custom_directory=true")

# PDF streams are deflated, so this is zlib whether it was asked for or not.
cme_port_feature(skia pdf
  SUMMARY "the PDF backend"
  IMPLIES zlib
  GN_ARGS "skia_enable_pdf=true"
  GN_CONFIRM "skia_enable_pdf=true")

cme_port_feature(skia svg
  SUMMARY "the SVG module, which reads XML with expat"
  DEPENDS expat
  GN_ARGS "skia_enable_svg=true" "skia_use_expat=true"
          "skia_use_system_expat=true"
  GN_CONFIRM "skia_use_system_expat=true")

cme_port_feature(skia skottie
  SUMMARY "the Lottie animation module"
  GN_ARGS "skia_enable_skottie=true")

function(cme_adapt_skia source binary)
  # Skia includes itself as "include/core/SkCanvas.h" -- a path relative to
  # the root of its own checkout, with nothing in it to say whose include
  # directory that is. In a project of any size that is a name waiting to
  # collide, and a consumer that writes it has said nothing about which
  # library it meant.
  #
  # So its include directory is offered a second time under a name of its
  # own, and a consumer writes <skia/core/SkCanvas.h>. Skia itself is
  # unchanged and still compiles against its own spelling, because the root
  # of the checkout is on the interface as well -- which is also how the
  # things outside include/, like modules/skottie/include, are still
  # reachable. The name is a link rather than a copy.
  cme_header_prefix(named skia "${source}/include")
  target_include_directories(skia_skia INTERFACE
    "$<BUILD_INTERFACE:${named}>" "$<BUILD_INTERFACE:${source}>")
  cme_export_variable(Skia SKIA_FOUND TRUE)
  cme_export_variable(Skia SKIA_LIBRARY Skia::skia)
  cme_export_variable(Skia SKIA_LIBRARIES Skia::skia)
  cme_export_variable(Skia SKIA_INCLUDE_DIR "${named};${source}")
  cme_export_variable(Skia SKIA_INCLUDE_DIRS "${named};${source}")
endfunction()

# What an installed Skia needs before this project can compile against it.
#
# Two things, and both are about spelling rather than about code.
#
# Skia's own headers say #include "include/core/SkCanvas.h", and that is what
# everything written against Skia says too. Debian rewrites those to
# <skia/core/...> as it installs them and puts them under /usr/include/skia,
# so the upstream spelling finds nothing. The directory is offered a second
# time under the name include/, and both spellings then work.
#
# And the macros. Skia's public headers are cut by SK_GANESH, SK_GL and the
# SK_CODEC_DECODES_* set, which the build passes on the command line and no
# installed file records. A consumer that does not define the same ones sees
# a different library than the one that was compiled -- different fields in
# the same class -- so the ones matching the features that were found to link
# are defined here.
function(cme_adapt_skia_system includes targets)
  set(arranged "")
  foreach(directory IN LISTS includes)
    if(EXISTS "${directory}/core/SkCanvas.h")
      cme_header_prefix(root include "${directory}")
      set(arranged "${root}")
    endif()
  endforeach()
  cme_enabled_features(skia features)
  set(defines "")
  if("gl" IN_LIST features)
    list(APPEND defines SK_GANESH SK_GL)
  endif()
  if("vulkan" IN_LIST features)
    list(APPEND defines SK_GANESH SK_VULKAN)
  endif()
  if("graphite" IN_LIST features)
    list(APPEND defines SK_GRAPHITE)
  endif()
  if("png" IN_LIST features)
    list(APPEND defines SK_CODEC_DECODES_PNG SK_CODEC_ENCODES_PNG)
  endif()
  if("jpeg" IN_LIST features)
    list(APPEND defines SK_CODEC_DECODES_JPEG SK_CODEC_ENCODES_JPEG)
  endif()
  if("webp" IN_LIST features)
    list(APPEND defines SK_CODEC_DECODES_WEBP SK_CODEC_ENCODES_WEBP)
  endif()
  if(defines)
    list(REMOVE_DUPLICATES defines)
  endif()
  foreach(target IN LISTS targets)
    if(NOT TARGET ${target})
      continue()
    endif()
    if(arranged)
      set_property(TARGET ${target} APPEND PROPERTY
                   INTERFACE_INCLUDE_DIRECTORIES "${arranged}")
    endif()
    foreach(define IN LISTS defines)
      set_property(TARGET ${target} APPEND PROPERTY
                   INTERFACE_COMPILE_DEFINITIONS "${define}")
    endforeach()
  endforeach()
  list(JOIN defines " " said)
  message(STATUS
    "cmake-everywhere: the installed Skia is used with ${said}")
endfunction()
